version: '3.8'

services:
  test:
    build: .
    volumes:
      - .:/app/klm_data_analytics  # Map the host directory
    working_dir: /app
    command: >
      sh -c "coverage run -m unittest discover -s tests &&
             coverage html -d /app/klm_data_analytics/coverage_results/"